## Numpy problems

## Using NumPy, create a 1D array of 20 random integers between 10 and50. Then, find the mean and standard deviation of the array.

In [3]:
import numpy as np

In [4]:
# Create a 1D array of 20 random integers between 10 and 50
random_array = np.random.randint(10,50,20)
print(random_array)

[34 39 42 23 35 28 26 45 42 28 19 36 48 35 33 10 38 25 10 36]


In [5]:
# Compute the mean and standard deviation
mean_value = np.mean(random_array)
print(mean_value)
std_dev = np.std(random_array)
print(std_dev)

31.6
10.239140588936163


## Create a 2D NumPy array of shape (6, 5) filled with random floatsbetween 0 and 1. Reshape this array to have shape (5, 6) and print both the original and reshaped arrays

In [7]:
# Generate a 6x5 array with random floats between 0 and 1
random_2d_array = np.random.rand(6, 5)
print(random_2d_array)

[[0.98805616 0.86989068 0.89472248 0.9495755  0.74970545]
 [0.90109541 0.19450018 0.2547858  0.01712155 0.64836595]
 [0.77894981 0.21536645 0.07492551 0.67216524 0.68625033]
 [0.04881141 0.22232759 0.55207146 0.51125834 0.56087494]
 [0.69799276 0.48986808 0.73785413 0.68362143 0.22014048]
 [0.37456788 0.95890028 0.65338069 0.03185146 0.05152482]]


In [8]:
# Reshape to 5x6
reshaped_array = random_2d_array.reshape(5, 6)
print(reshaped_array)

[[0.98805616 0.86989068 0.89472248 0.9495755  0.74970545 0.90109541]
 [0.19450018 0.2547858  0.01712155 0.64836595 0.77894981 0.21536645]
 [0.07492551 0.67216524 0.68625033 0.04881141 0.22232759 0.55207146]
 [0.51125834 0.56087494 0.69799276 0.48986808 0.73785413 0.68362143]
 [0.22014048 0.37456788 0.95890028 0.65338069 0.03185146 0.05152482]]


## Create a 2D array of shape (5, 5) filled with numbers from 1 to 25.Extract a subarray that includes rows 2 to 4 and columns 1 to 3.


In [10]:
array_1 = np.arange(1,26).reshape(5,5)
print(array_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [11]:
subarray = array_1[1:4, 0:3]
print(subarray)

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


##  Generate two 1D arrays A and B, each containing 10 random integersbetween 1 and 100. Add the arrays together, then multiply the result by 2. Showthe results of each operation.


In [13]:
# Generate two 1D arrays A and B with 10 random integers between 1 and 100
A = np.random.randint(1, 101, 10)
print(A)
B = np.random.randint(1, 101, 10)
print(B)

[64  7 86 85 26  8 22 40 54  4]
[ 5 44  7 42  5 21 59 62 30 10]


In [14]:
sum_array = A+B
print(sum_array)
mult_array = sum_array*2
print(mult_array)


[ 69  51  93 127  31  29  81 102  84  14]
[138 102 186 254  62  58 162 204 168  28]


## Create a 2D array A of shape (3, 4) filled with random integers between1 and 10. Create a 1D array B of shape (4,) with values [1, 2, 3, 4]. Add the 1D arrayto the 2D array and explain how broadcasting works in this case.

In [16]:
A=np.random.randint(1,11,(3,4))
print(A)

[[ 9 10  4  7]
 [ 7  3  5  2]
 [ 9  6  7  5]]


In [17]:
B=np.array([1,2,3,4])
print(B)

[1 2 3 4]


In [18]:
sum_array=A+B
print(sum_array)

[[10 12  7 11]
 [ 8  5  8  6]
 [10  8 10  9]]


## : Create a 3x3 matrix of random integers between 1 and 100. Find therow with the maximum sum, and then the maximum value in that row.


In [20]:
array_3d_matrix = np.random.randint(1,101,(3,3))
print(array_3d_matrix)

[[28 91 25]
 [52 11 19]
 [56 95 67]]


In [21]:
sum_row = np.sum(array_3d_matrix,axis = 1)
print(sum_row) # To find the sum of index

[144  82 218]


In [22]:
index_value = np.argmax(sum_row)
print(index_value)

2


In [23]:
max_value = np.max(array_3d_matrix[index_value])
print(max_value)

95


## Create two 2D arrays A and B, both of shape (2, 2), filled with randomintegers. Compute the matrix multiplication of A and B using np.dot().





In [25]:
A = np.random.randint(1,15,(2,2))
B = np.random.randint(1,20,(2,2))
print("A =\n",A,'\n')
print("B=\n" ,B,'\n')

A =
 [[5 9]
 [4 3]] 

B=
 [[18  7]
 [ 1 12]] 



In [26]:
matrix_multi = np.dot(A,B)
print(matrix_multi)


[[ 99 143]
 [ 75  64]]


## Create an array of shape (6, 6) with random integers between 1 and 50.Using boolean indexing, extract all values greater than 25.

 

In [28]:
array = np.random.randint(1,51,(6,6))
print(array)

[[27 16 15  6 21 22]
 [ 5 32 28 26 14 45]
 [15 21 43 30 16 24]
 [ 6 47 16 36 10 13]
 [46 29 44 13 44  7]
 [40  4 36 29 26  9]]


In [29]:
max_array=array[array>25]
print(max_array)

[27 32 28 26 45 43 30 47 36 46 29 44 44 40 36 29 26]


## Create a 5x5 array of random floats between 0 and 1. Calculate themedian and variance along the columns and rows separately

In [31]:
matrix = np.random.rand(5,5)
print(matrix)

[[0.90456274 0.96693231 0.80176239 0.4106054  0.31320809]
 [0.69023637 0.79945511 0.77613694 0.19467642 0.48323926]
 [0.87503128 0.52153755 0.12537374 0.32837521 0.86040692]
 [0.03741875 0.17601421 0.19002601 0.46823421 0.92120744]
 [0.4321154  0.34284204 0.83200049 0.3610394  0.6361565 ]]


In [32]:
matrix_rowmedian= np.median(matrix,axis=1)
print(matrix_rowmedian)

[0.80176239 0.69023637 0.52153755 0.19002601 0.4321154 ]


In [33]:
matrix_colmedian=np.median(matrix,axis=0)
print(matrix_colmedian)

[0.69023637 0.52153755 0.77613694 0.3610394  0.6361565 ]


In [34]:
matrix_rowvariance=np.var(matrix,axis=1)
print(matrix_rowvariance)

[0.07093854 0.0512473  0.08638488 0.09869179 0.03504206]


In [35]:
matrix_colvariance=np.var(matrix,axis=0)
print(matrix_colvariance)

[0.10409817 0.0838011  0.10076264 0.00846676 0.05179961]


## Generate a 3x3 matrix of random integers between 1 and 10. Performthe following element-wise operations: subtract 2 from each element, square eachelement, and compute the reciprocal of each element.

In [50]:
matrix = np.random.randint(1,11,(3,3))
print(matrix)

[[10 10  1]
 [ 5  7  7]
 [10  3  9]]


In [52]:
sub_array = matrix -2
print(sub_array)

[[ 8  8 -1]
 [ 3  5  5]
 [ 8  1  7]]


In [54]:
square_array = matrix**2
print(square_array)

[[100 100   1]
 [ 25  49  49]
 [100   9  81]]


In [60]:
reciprocal_array=1/matrix
print(reciprocal_array)

[[0.1        0.1        1.        ]
 [0.2        0.14285714 0.14285714]
 [0.1        0.33333333 0.11111111]]


In [64]:
# using reciprocal
rec_array= np.reciprocal(matrix.astype(float))
print(rec_array)

[[0.1        0.1        1.        ]
 [0.2        0.14285714 0.14285714]
 [0.1        0.33333333 0.11111111]]


In [67]:
import pandas as pd

## 1 Basic Exploration
### Load the dataset into a Pandas DataFrame. Display:
#### ○ The first 10 rows
#### ○ The total number of rows and columns
#### ○ Summary statistics for numerical columns

In [75]:
df = pd.read_csv("auto-mpg.csv")
print("First 10 rows:")
df.head(10)

First 10 rows:


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [77]:
print("Total number of rows and columns:")
df.shape

Total number of rows and columns:


(398, 9)

In [79]:
print("Summary statistics for numerical columns:")
df.describe()

Summary statistics for numerical columns:


mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

## 2 Filtering and Indexing


In [83]:
df[(df["model year"] ==75) & (df["weight"]<3000)][["car name","weight","mpg"]]


car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

## 3 Handling Missing Data

In [85]:
#3 
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [87]:
hp =df[(df['horsepower']!='?')]['horsepower'].astype(int).median()
hps= df['horsepower'].values
hps[hps=='?']=hp
df['horsepower']=hps.astype(int)
df['horsepower']


0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: int32

In [89]:
df


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

## 4 Data Transformation

In [91]:
#4
df["power_to_weight_ratio"] = df["horsepower"]/df["weight"]
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

## 5 Group By group the cars by origin and calculate the mean mpg for each grou

In [93]:
#5
df_grouped = df.groupby(by="origin")['mpg'].mean()
df_grouped.head()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

## 6 Sorting Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

In [101]:
#6
df_mpg_sort = df.sort_values(by= "mpg",ascending = False)
df_mpg_sort.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0          65    2110          17.9   
329  44.6          4          91.0          67    1850          13.8   
325  44.3          4          90.0          48    2085          21.7   
394  44.0          4          97.0          52    2130          24.6   
326  43.4          4          90.0          48    2335          23.7   
244  43.1          4          90.0          48    1985          21.5   
309  41.5          4          98.0          76    2144          14.7   
330  40.9          4          85.0          93    1835          17.3   
324  40.8          4          85.0          65    2110          19.2   
247  39.4          4          85.0          70    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050681  
324               0.030806  
247               0.033816

 ## 7 Apply Function Create a new column performance_score using a custom function:
#### def performance_score(row):
####    return row['mpg'] * row['acceleration'] / row['weight']
### Apply this function to each row and store the result in the new colum

In [105]:
#7
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']
    

In [109]:
df['performance_score'] =df.apply(performance_score,axis=1)
df[['mpg','acceleration','weight','performance_score']].head()

mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754

### 8 Visualization Preparation

In [111]:
#8
df_summary =df.groupby(by='model year')[['mpg','weight','horsepower']].mean()
df_summary

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.535714
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.185185
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.551724
81          30.334483  2522.931034   81.448276
82          31.709677  2453.548387   81.838710

### 9 Exporting Data

In [113]:
#9
new_dff =df[df['mpg']>30][['mpg','cylinders','horsepower','weight']]
new_dff.to_csv("high_mpg_cars.csv")

### 10 .Finding Anomalies

In [115]:
#10
Q1 =df['mpg'].quantile(0.25)
Q3 =df['mpg'].quantile(0.75)
IQR = Q3 -Q1

lower_bound = Q1 -1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['mpg']<lower_bound) | (df['mpg']>upper_bound)]
outliers_df = outliers[['car name','mpg','model year']]

print("Cars classified as outliers:")
(outliers_df)

Cars classified as outliers:


car name   mpg  model year
322  mazda glc  46.6          80